[build-system]
requires = ["setuptools>=40.8.0", "wheel"]

[project]
name = "llm_finetune"
version = "0.1.0"
description = "demo for multinode llm finetune thai-to-gloss"
requires-python = ">=3.8"
classifiers = ["Programming Language :: Python :: 3"]
dependencies = [
    "numpy",
    "pandas",
    "tqdm",
    "jupyter",
    "transformers",
    "datasets",
    "accelerate",
    "peft",
    "trl[vllm]",
    "sentencepiece",
    "hydra-core",
    "protobuf>=3.19.6,<6",
    "scikit-learn",
    "deepspeed",
    "wandb",
    "evaluate",
    "rouge_score"
]